spring:
  profiles:
    active: dev,jwt

  jpa:
    hibernate:
      ddl-auto: none   # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
        #        format_sql: true # 보기 좋은 형식으로 출력
        use_sql_comments: true

server:
  servlet:
    context-path: /api

security:
  permit-all-paths:
    paths:
      POST:
        - /api/auth
        - /api/users
      GET:
        - /**
#        health

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: "jaesangYSecretKeyjaesangYInProduction64BytesjaesangY"
  access-token-expiration-ms: 1800000  # 30분
  refresh-token-expiration-ms: 2592000000 # 30일