spring:
  datasource:
    url: jdbc:mysql://my-db.c7ygay4i4a22.ap-northeast-2.rds.amazonaws.com:3306/community?serverTimezone=UTC&useSSL=false
    username: root
    password: root0616
    driver-class-name: com.mysql.cj.jdbc.Driver
