spring:
  profiles:
    active: dev,jwt

  jpa:
    hibernate:
      ddl-auto: none   # 개발 중에는 create / create-drop / update 중 선택
    properties:
      hibernate:
        format_sql: true # 보기 좋은 형식으로 출력
        use_sql_comments: true

server:
  servlet:
    context-path: /api

security:
  permit-all-paths:
    paths:
      POST:
        - /api/auth
        - /api/users
      GET:
        - /api/health
        - /api/posts/*
        - /api/comments
      PUT:
        - /api
      PATCH:
        - /api
      DELETE:
        - /api

logging:
  level:
    org.hibernate.SQL: debug

jwt:
  secret: "jaesangYSecretKeyjaesangYInProduction64BytesjaesangY"
  access-token-expiration-ms: 9999900000  # test
  #  access-token-expiration-ms: 3600000  # 1시간
  refresh-token-expiration-ms: 2592000000 # 30일

# File Storage Settings
file:
  # 파일이 실제로 저장될 로컬 시스템 경로
  upload-dir: ./uploads/images/
  # 클라이언트가 이미지에 접근할 때 사용할 서버 기본 URL
  base-url: http://localhost:8080
